### ISSUE TITLE
sort z, y and x alphabetic in channel

### ISSUE THREAD

**Issue by Desour** [HybridDog/colour_carrier#2]
Pro:
- It would be not that confusing.

Contra:
- It could break existing stuff.

**Comment by Desour** [comment]
Ok, it won't be sorted. I'll add extra channels for a nice sort, the old scheme will be left there, too.
So, `"colour_carrier/"..pos.z .."/"..pos.y .."/"..pos.x` will work.
But also one of these:
- `"colour_carrier:"..pos.x ..","..pos.y ..","..pos.z`
- `"colour_carrier("..pos.x ..","..pos.y ..","..pos.z..")"`
- `"colour_carrier:"..pos.x ..";"..pos.y ..";"..pos.z`
- `"colour_carrier("..pos.x ..";"..pos.y ..";"..pos.z..")"`

Which one should be chosen? Or should be two or more of them allowed?

**Comment by HybridDog** [comment]
kein Strichpunkt,
man könnte mit * angeben, dass eine Koordinate nicht berücksichtigt wird, z.B. ```*,1,*```, um alle mit y = 1 anzusprechen

**Comment by Desour** [comment]
Dann wäre es aber auch gut, wenn man von einer bestimmten position zu einer anderen machen könnte.
=>
- `"colour_carrier:"..pos.x..","..pos.y ..","..pos.z`, wobei pos auch `* sein kann`
- und `"colour_carrier("..pos1.x ..","..pos1.y ..","..pos1.z.."),("..pos2.x ..","..pos2.y ..","..pos2.z..")"`
Oder vielleicht mit geschweiften Klammern `{` `}` oder eckigen `[` `]`?

**Comment by HybridDog** [comment]
Man könnte auch pdisc benutzen, wodurch der Spieler die Bedingungen selbst programmieren kann.

**Comment by Desour** [comment]
Das wäre dann aber zu aufwendig. Außerdem kann man ja auch mit einem luacontroller Ähnliches erreichen.

Ich denke, folgendes wäre gut:
- `"colour_carrier("..pos1.x ..","..pos1.y ..","..pos1.z.."),("..pos2.x ..","..pos2.y ..","..pos2.z..")"` (pos1 < pos2) `*` = -/+unendlich
- und `"colour_carrier("..pos.x ..","..pos.y ..","..pos.z..")"` (pos = pos1 = pos2) `*` = keine begrenzung durch diese Achse
- und die bereits vorhandenen: `"colour_carrier_all"` und `"colour_carrier/"..pos.z .."/"..pos.y .."/"..pos.x`

Die Klammern bleiben rund. Grund dafür ist, dass das oberste Kanalformat sehr an die Intervallschreibweise von Mengen der Mathematik erinnert und man auf die Idee kommen könnte, dass man die Klammern ein- oder ausschließend macht.

Ich hab auch schon Ideen, wie man das jeweils im Code umstetzt.

**Comment by Desour** [comment]
#5
